### ISSUE TITLE
Running failure

### ISSUE THREAD

**Issue by JQVazquez** [JustinChu/JupiterPlot#34]
Hello, I found repetitively this error, with different parameters configuration. Please, any advice or suggestion? Thank you in advance.
(base) user@USER:~/JupiterPlot-1.0$ perl jupiter name=xxx ref=/GCF_00000xxxxx.x_12X_genomic_CHR.fasta fa=xxx_consensus_radtag_corrected.fasta ng=10 maxGap=500000 minBundleSize=50000 m=10000000 i=0 t=20 g=100 gScaff=100000
bwa mem -t 20 -x intractg xxx_reference.fa xxx-agp.fa > xxx-agp.sam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 20 -x intractg xxx_reference.fa xxx-agp.fa
[main] Real time: 0.240 sec; CPU: 0.196 sec
grep -v XA xxx-agp.sam | grep -v '^@' | awk '{if($5 > 50 || $5 == "" ) print}' | perl /user/JupiterPlot-1.0/bin/samToBed.pl > xxx-agp.bed
make: *** [jupiter:82: xxx-agp.bed] Error 1
make: *** Deleted file 'xxx-agp.bed'
rm xxx_reference.fa.bwt

**Comment by JustinChu** [comment]
Couple things:

- I suspect is it is something to due to your input. What kind of genome are you references (approximated size and chromosome sizes).
- The command you ran with `perl` should not be needed. It is a make file. I'm somewhat surprised it ran at all.
- You seem to the fairly old release version of the code. Try using the master branch version of the codebase. There were some bugfixes for certain system configurations and edge cases.

**Comment by JQVazquez** [comment]
> Couple things:
> 
> * The command you ran with `perl` should not be needed. It is a make file. I'm somewhat surprised it ran at all.
> * You seem to the fairly old release version of the code. Try using the master branch version of the codebase. There were some bugfixes for certain system configurations and edge cases.
> * It may be due to something in your input. though I can't confirm without knowing more. What kind of genome are you references (approximated size and chromosome sizes).
> * When rerunning clear the working directory again to make sure no lingering files from previous runs at different parameters are interfering with the run.

Solved and running. It was an input issue. Thanks a lot.
